#pragma once

#ifndef VIRTUALCAMERA_MEDIASOURCE_H
#define VIRTUALCAMERA_MEDIASOURCE_H

#include <initguid.h>

#include "VirtualCameraShared.h"

// {EEA24C6E-6EAD-4D1F-9D1A-CE0F21C91867}
DEFINE_GUID(
    CLSID_LiveCastVirtualCameraMediaSource,
    0xeea24c6e,
    0x6ead,
    0x4d1f,
    0x9d,
    0x1a,
    0xce,
    0x0f,
    0x21,
    0xc9,
    0x18,
    0x67);

static constexpr LPCWSTR VIRTUALCAMERAMEDIASOURCE_CLSID = virtual_camera::kMediaSourceClsidString;
static constexpr LPCWSTR VIRTUALCAMERAMEDIASOURCE_FRIENDLYNAME = virtual_camera::kFriendlyName;

static const GUID PROPSETID_SIMPLEMEDIASOURCE_CUSTOMCONTROL =
{0x0ce2ef73, 0x4800, 0x4f53, {0x9b, 0x8e, 0x8c, 0x06, 0x79, 0x0f, 0xc0, 0xc7}};

enum
{
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORING = 0,
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_END
};

enum
{
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_GRAYSCALE = 0x0FFFFFF,
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_RED = 0x0FF0000,
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_GREEN = 0x000FF00,
    KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_BLUE = 0x00000FF
};

typedef struct {
    uint32_t ColorMode;
} KSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_S, *PKSPROPERTY_SIMPLEMEDIASOURCE_CUSTOMCONTROL_COLORMODE_S;

#endif
